AWSTemplateFormatVersion: 2010-09-09
Description: Create an IAM Service Role to be assumed automation process.

Parameters:
  RoleName:
    Type: String
    Description: "IAM Service Role name"

Resources:
  ReadOnlyAccessIamServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      Description: "IAM Service Role to be assumed by automation processes."
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::123456789012:root
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/ReadOnlyAccess"
